name: Run Bot Winner DZ

on:
  schedule:
    - cron: '0 */6 * * *' # S'exécute toutes les 6 heures
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Exécution du Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py

      - name: Sauvegarder la mémoire du bot
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add seen_products.json
          git commit -m "Auto-update seen products [skip ci]" || exit 0
          git push
